### PR TITLE
Add OpenTelemetry collector for Honeycomb on Dev cluster

### PR DESCRIPTION
**Pull request by tshaynik**
## Summary by CodeRabbit

- **New Features**
	- Introduced local variables and functionality for configuring the OpenTelemetry Collector on Kubernetes.
	- Deployed Honeycomb services with enhanced Kubernetes resource management.
	- Implemented conflict resolution settings for core EKS add-ons.

- **Improvements**
	- Updated AWS region-specific Terraform configurations for better resource management in EKS.
	- Refined role definitions for AWS authentication in the EKS cluster.

- **Bug Fixes**
	- Removed unnecessary `--profile` arguments from Kubernetes provider configurations to streamline operations.

### CODE REVIEW

**Comment by Fentonhaslam** [comment]
atlantis unlock

**Comment by Fentonhaslam** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/eks/cluster

**Comment by renebarbosafl** [comment]
atlantis plan

**Review by renebarbosafl — APPROVED** [review]

**Pull request merged**
