### PR TITLE
chore: adding expose trait on cardano-node-preview

### PR DESCRIPTION
**Pull request by renebarbosafl**
Adding a LoadBalancer for `cardano-node-preview`.

### CODE REVIEW

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis apply

**Review by shlevy — APPROVED** [review]

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis apply

**Pull request merged**
