### PR TITLE
chore: reorganizing repo structure

### PR DESCRIPTION
**Pull request by renebarbosafl**
## Summary by CodeRabbit

- **Infrastructure Updates**
	- Improved configuration paths for various dependencies across our AWS infrastructure.
	- Streamlined provider configuration retrieval methods for enhanced stability.
	- Refined Terraform module sources and dependencies for better infrastructure management.

### CODE REVIEW

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/aws/global/iam/roles/atlantis

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/aws/global/iam/roles/atlantis -w infra_aws_global_iam_roles_atlantis

**Comment by renebarbosafl** [comment]
atlantis unlock

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/aws/global/iam/roles/atlantis -w infra_aws_global_iam_roles_atlantis

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis plan

**Review by tshaynik — COMMENTED** [review]
I don't think that `grafana` should be under `infra/aws`, since it has nothing to do with `aws`. Why not just move `atlantis` under `infra/`, without adding an extra layer of nesting for everything currently under `infra`?

**Comment by renebarbosafl** [comment]
atlantis unlock

**Pull request closed without merging**
