### PR TITLE
refact: using vpc module to create rds dependencies

### PR DESCRIPTION
**Pull request by renebarbosafl**
## Summary by CodeRabbit

- **New Features**
    - Expanded the VPC setup to include database subnets for enhanced infrastructure capabilities.
    - Updated network configurations for better performance and manageability.

### CODE REVIEW

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/eks/kubevela-addons -w infra_us-east-1_dev_eks_kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan -d nfra/us-east-1/prod/eks/green/kubevela-addons -w infra_us-east-1_prod_eks_green_kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addons -w infra_us-east-1_prod_eks_green_kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan -destroy -d infra/us-east-1/dev/rds/subnet-group

**Comment by renebarbosafl** [comment]
atlantis plan -destroy -d infra/us-east-1/dev/rds/subnet-group -w infra_us-east-1_dev_rds_subnet-group

**Comment by renebarbosafl** [comment]
atlantis plan -destroy -d infra/us-east-1/dev/rds/subnet-group

**Comment by renebarbosafl** [comment]
atlantis plan -destroy -d infra/us-east-1/dev/rds/subnet-group

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/dev/rds/subnet-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/rds/subnet-group

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/vpc

**Comment by renebarbosafl** [comment]
atlantis unlock

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/eks/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/dev/vpc

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/eks/green/kubevela-addons

**Review by falcucci — APPROVED** [review]

**Pull request merged**
