### PR TITLE
chore: updating eks auth

### PR DESCRIPTION
**Pull request by renebarbosafl**
## Summary by CodeRabbit

- **Chores**
	- Removed a team member from the account access list.
- **New Features**
	- Enhanced IAM roles and user management for EKS clusters, including a new role for deployment automation.

### CODE REVIEW

**Comment by renebarbosafl** [comment]
atlantis plan -d  infra/us-east-1/prod/eks/green/eks

**Comment by renebarbosafl** [comment]
atlantis plan -d  infra/us-east-1/prod/eks/green/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addon

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/eks/green/kubevela-addons

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/eks/green/eks

**Comment by renebarbosafl** [comment]
@coderabbitai review

**Review by falcucci — APPROVED** [review]

**Pull request merged**
