### PR TITLE
chore: remove old infra

### PR DESCRIPTION
**Pull request by renebarbosafl**
## Summary by CodeRabbit

- **Refactor**
  - Updated the environment configuration for enhanced service stability and performance.

### CODE REVIEW

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/prod-us-east-1/vpc -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/peering/dapps-old -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/peering/dapps-old -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/security-group-jingles -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/rds/bastion/ec2-instance -- -destroy
atlantis plan -d infra/us-east-1/rds/bastion/key-pair -- -destroy
atlantis plan -d infra/us-east-1/rds/bastion/security-group -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/rds/bastion/ec2-instance -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/bastion/ec2-instance -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/bastion/ec2-instance -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/bastion/key-pair  -- -destroy

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/bastion/security-group  -- -destroy

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db -- -destroy

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db -- -destroy

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/rds/prod-marlowe-runtime-db

**Comment by renebarbosafl** [comment]
atlantis plan -d infra/us-east-1/prod/rds/security-group-jingles -- -destroy

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/rds/security-group-jingles

**Comment by renebarbosafl** [comment]
@coderabbitai review

**Review by tshaynik — APPROVED** [review]

**Review by shlevy — APPROVED** [review]

**Pull request merged**
