### PR TITLE
fix: crossplane

### PR DESCRIPTION
**Pull request by renebarbosafl**
## Summary by CodeRabbit

- **Refactor**
	- Updated cluster service account mapping for improved resource allocation.
	- Modified subnet group declaration for enhanced configuration.

### CODE REVIEW

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis plan

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/global/iam/roles/crossplane

**Comment by renebarbosafl** [comment]
atlantis apply -d infra/us-east-1/prod/rds/subnet-group

**Review by ce0la — APPROVED** [review]

**Pull request merged**
